source 'https://rubygems.org'
gem 'nanoc', '~> 4'

gem 'less', '~> 2.6.0'
gem 'nokogiri', '~> 1.6.6.2'
gem 'therubyracer', '~> 0.12.2'
gem 'yuicompressor', '~> 1.3.3'

group :development do
    gem 'adsf', '~> 1.2.0'
end
