source 'https://rubygems.org'
gem 'nanoc', '~> 4'

gem 'less', '~> 2.6'
gem 'nokogiri', '~> 1.12'
gem 'therubyracer', '~> 0.12'
gem 'yuicompressor', '~> 1.3'

group :development do
    gem 'adsf', '~> 1.2.0'
end
